# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '9.0'

target 'Agile24' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Agile24
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.0.0'
  pod 'SwiftyJSON', :git =>'https://github.com/SwiftyJSON/SwiftyJSON.git'

  target 'Agile24UITests' do
    inherit! :search_paths
    # Pods for testing

  end

end
